//! Handwritten DS005 operations.

use crate::protocol::{Query, items, source_status};
use crate::request::RequestParts;
use crate::values::{CompactDate, CompanyCode};
use crate::wire::decode::{ObjectDecoder, decode_array, decode_source_status, decode_xml_array};
use crate::{
    OperationIdentity, PrepareError, PreparedRequest, ResponseDecodeError, SourceStatus,
    SourceValue,
};

mod other_asset_transactions_and_putback_options;
pub use other_asset_transactions_and_putback_options::*;
mod creditor_bank_management_discontinuations;
pub use creditor_bank_management_discontinuations::*;
mod write_down_contingent_capital_securities_issuance_decisions;
pub use write_down_contingent_capital_securities_issuance_decisions::*;
mod treasury_stock_acquisition_decisions;
pub use treasury_stock_acquisition_decisions::*;
mod treasury_stock_disposal_decisions;
pub use treasury_stock_disposal_decisions::*;
mod treasury_stock_acquisition_trust_contract_execution_decisions;
pub use treasury_stock_acquisition_trust_contract_execution_decisions::*;
mod treasury_stock_acquisition_trust_contract_termination_decisions;
pub use treasury_stock_acquisition_trust_contract_termination_decisions::*;
mod business_acquisition_decisions;
pub use business_acquisition_decisions::*;
mod business_transfer_decisions;
pub use business_transfer_decisions::*;
mod tangible_asset_acquisition_decisions;
pub use tangible_asset_acquisition_decisions::*;
mod tangible_asset_transfer_decisions;
pub use tangible_asset_transfer_decisions::*;
mod other_company_equity_securities_acquisition_decisions;
pub use other_company_equity_securities_acquisition_decisions::*;
mod other_company_equity_securities_transfer_decisions;
pub use other_company_equity_securities_transfer_decisions::*;
mod stock_related_bond_acquisition_decisions;
pub use stock_related_bond_acquisition_decisions::*;
mod stock_related_bond_transfer_decisions;
pub use stock_related_bond_transfer_decisions::*;
mod company_merger_decisions;
pub use company_merger_decisions::*;
mod company_split_decisions;
pub use company_split_decisions::*;
mod company_split_merger_decisions;
pub use company_split_merger_decisions::*;
mod share_exchange_transfer_decisions;
pub use share_exchange_transfer_decisions::*;
mod default_events;
pub use default_events::*;
mod business_suspensions;
pub use business_suspensions::*;
mod rehabilitation_proceeding_applications;
pub use rehabilitation_proceeding_applications::*;
mod dissolution_events;
pub use dissolution_events::*;
mod paid_in_capital_increase_decisions;
pub use paid_in_capital_increase_decisions::*;
mod bonus_share_issue_decisions;
pub use bonus_share_issue_decisions::*;
mod combined_paid_in_and_bonus_share_issue_decisions;
pub use combined_paid_in_and_bonus_share_issue_decisions::*;
mod capital_reduction_decisions;
pub use capital_reduction_decisions::*;
mod creditor_bank_management_commencements;
pub use creditor_bank_management_commencements::*;
mod lawsuit_filings;
pub use lawsuit_filings::*;
mod overseas_market_listing_decisions;
pub use overseas_market_listing_decisions::*;
mod overseas_market_delisting_decisions;
pub use overseas_market_delisting_decisions::*;
mod overseas_market_listings;
pub use overseas_market_listings::*;
mod overseas_market_delistings;
pub use overseas_market_delistings::*;
mod convertible_bond_issuance_decisions;
pub use convertible_bond_issuance_decisions::*;
mod bond_with_warrants_issuance_decisions;
pub use bond_with_warrants_issuance_decisions::*;
mod exchangeable_bond_issuance_decisions;
pub use exchangeable_bond_issuance_decisions::*;
