package rust

import (
	"fmt"
	"strings"

	"github.com/cpaikr/opendart/internal/sdkgen/model"
	"github.com/cpaikr/opendart/internal/sdkgen/ownership"
)

// Artifacts contains both independently owned Rust product trees.
type Artifacts struct {
	SDK map[string][]byte
	CLI map[string][]byte
}

// RenderArtifacts renders the SDK and CLI adapters from one normalized build.
func RenderArtifacts(source model.ArtifactSet) (Artifacts, error) {
	sdk, err := Render(source.SDK)
	if err != nil {
		return Artifacts{}, err
	}
	cli, err := renderCLI(source.CLI)
	if err != nil {
		return Artifacts{}, err
	}
	return Artifacts{SDK: sdk, CLI: cli}, nil
}

func renderCLI(source model.CLIModel) (map[string][]byte, error) {
	if source.SchemaVersion != model.CLIProjectionSchemaVersion || source.Checksum == "" || len(source.Operations) == 0 {
		return nil, fmt.Errorf("render Rust CLI: invalid model schema, checksum, or inventory")
	}
	return map[string][]byte{
		ownership.CLIFilename: []byte(ownership.CLIMarker(source.SchemaVersion)),
		"mod.rs":              []byte(renderCLIModule(source)),
		"catalog.rs":          []byte(renderCLICatalog(source)),
		"command.rs":          []byte(renderCLICommand(source)),
		"dispatch.rs":         []byte(renderCLIDispatch(source)),
	}, nil
}

func cliHeader(source model.CLIModel) string {
	return "// @generated by opendart-tool; DO NOT EDIT.\n" +
		fmt.Sprintf("// cli-generator-schema: %d\n", source.SchemaVersion) +
		"// cli-projection-sha256: " + source.Checksum + "\n\n"
}

func renderCLIModule(source model.CLIModel) string {
	return cliHeader(source) + fmt.Sprintf(
		"pub(crate) const GENERATOR_SCHEMA: u32 = %d;\npub(crate) const PROJECTION_CHECKSUM: &str = %s;\n\npub(crate) mod catalog;\npub(crate) mod command;\npub(crate) mod dispatch;\n",
		source.SchemaVersion, quote(source.Checksum),
	)
}

func renderCLICatalog(source model.CLIModel) string {
	var output strings.Builder
	output.WriteString(cliHeader(source))
	output.WriteString("use crate::discovery::{CALL_FLAGS, FlagSpec, InvocationSpec, OperationSpec, OutputSpec, RepresentationSpec, ResponseField, ResponseShape};\n\n")
	output.WriteString("pub(crate) const OPERATIONS: &[OperationSpec] = &[\n")
	for _, operation := range source.Operations {
		output.WriteString("    OperationSpec {\n")
		fmt.Fprintf(&output, "        name: %s,\n        logical_id: %s,\n        group: %s,\n        api_id: %s,\n        guide_url: %s,\n        description: %s,\n",
			quote(operation.Name), quote(operation.LogicalID), quote(operation.Group), quote(operation.APIID), quote(operation.GuideURL), quote(operation.Description))
		fmt.Fprintf(&output, "        invocation: InvocationSpec { argv_prefix: &[\"call\", %s], required_env: &[\"OPENDART_API_KEY\"] },\n", quote(operation.Name))
		output.WriteString("        execution_flags: CALL_FLAGS,\n        flags: &[\n")
		for _, parameter := range operation.Parameters {
			occurrence, kind := "once", "string"
			if parameter.Shape == model.StringArray {
				occurrence, kind = "repeat", "string_list"
			}
			fmt.Fprintf(&output, "            FlagSpec { name: %s, id: %s, sdk_field: %s, description: %s, required: %t, value_kind: %s, occurrence: %s, min_items: %s, max_items: %s },\n",
				quote("--"+parameter.Flag), quote(parameter.SDKField), quote(parameter.SDKField), quote(parameter.Description), parameter.Required, quote(kind), quote(occurrence), rustIntOption(parameter.MinItems), rustIntOption(parameter.MaxItems))
		}
		output.WriteString("        ],\n        representations: &[\n")
		for _, representation := range operation.Representations {
			selector := "&[]"
			if representation.Selector {
				selector = fmt.Sprintf("&[\"--representation\", %s]", quote(string(representation.Name)))
			}
			outputSpec := "OutputSpec::Stdout"
			if representation.Name == model.RepresentationZIP {
				outputSpec = "OutputSpec::Artifact { argument_argv: &[\"--output\", \"<path>\"], required: true, existing_destination: \"reject\", limit_argument_argv: &[\"--artifact-limit-bytes\", \"<positive-integer>\"], limit_required: false, default_limit_bytes: 536_870_912 }"
			}
			fmt.Fprintf(&output, "            RepresentationSpec { name: %s, physical_id: %s, response_type: %s, response_shape: %s, selector_argv: %s, output: %s },\n",
				quote(string(representation.Name)), quote(representation.PhysicalID), quote(representation.ResponseType), renderCLIResponseShape(representation.ResponseShape), selector, outputSpec)
		}
		output.WriteString("        ],\n    },\n")
	}
	output.WriteString("];\n\npub(crate) fn operation(name_or_id: &str) -> Option<&'static OperationSpec> {\n    OPERATIONS.iter().find(|operation| operation.name == name_or_id || operation.logical_id == name_or_id)\n}\n")
	return output.String()
}

func renderCLIResponseShape(shape model.CLIResponseShape) string {
	switch shape.Kind {
	case "object":
		var output strings.Builder
		fmt.Fprintf(&output, "ResponseShape::Object { additional_fields: %t, fields: &[", shape.AdditionalFields)
		for _, field := range shape.Fields {
			fmt.Fprintf(&output, "ResponseField { name: %s, required: %t, description: %s, shape: %s },",
				quote(field.Name), field.Required, rustStringOption(field.Description), renderCLIResponseShape(field.Shape))
		}
		output.WriteString("] }")
		return output.String()
	case "array":
		return "ResponseShape::Array { items: &(" + renderCLIResponseShape(*shape.Items) + ") }"
	case "source_value":
		return "ResponseShape::SourceValue"
	case "source_status":
		return "ResponseShape::SourceStatus"
	case "binary":
		return "ResponseShape::Binary"
	default:
		panic("unsupported CLI response shape")
	}
}

func renderCLICommand(source model.CLIModel) string {
	return cliHeader(source) + `use clap::{Arg, ArgAction, Command};

use crate::command::execution_arguments;
use super::catalog::OPERATIONS;

pub(crate) fn command() -> Command {
    let operations = Command::new("operations")
        .about("Discover generated OpenDART operations")
        .subcommand_required(true)
        .subcommand(Command::new("list").about("List logical operations"))
        .subcommand(
            Command::new("describe")
                .about("Describe one logical operation")
                .arg(Arg::new("operation").required(true).value_name("OPERATION")),
        );
    let mut call = Command::new("call")
        .about("Prepare and execute one typed OpenDART operation")
        .subcommand_required(true);
    for operation in OPERATIONS {
        let mut generated = Command::new(operation.name)
            .alias(operation.logical_id)
            .about(operation.description);
        for flag in operation.flags {
            let action = if flag.occurrence == "repeat" { ArgAction::Append } else { ArgAction::Set };
            generated = generated.arg(
                Arg::new(flag.id)
                    .long(flag.name.trim_start_matches("--"))
                    .help(flag.description)
                    .required(flag.required)
                    .num_args(1)
                    .action(action),
            );
        }
        let has_selector = operation.representations.iter().any(|representation| !representation.selector_argv.is_empty());
        let is_binary = operation.representations.iter().any(|representation| representation.name == "zip");
        if has_selector {
            generated = generated.arg(
                Arg::new("representation")
                    .long("representation")
                    .required(true)
                    .num_args(1)
                    .value_parser(["json", "xml"]),
            );
        }
        if is_binary {
            generated = generated.arg(Arg::new("output").long("output").required(true).num_args(1));
        }
        generated = execution_arguments(generated, is_binary);
        call = call.subcommand(generated);
    }
    Command::new("opendart")
        .about("Call OpenDART through the typed Rust SDK")
        .version(env!("CARGO_PKG_VERSION"))
        .propagate_version(true)
        .subcommand(operations)
        .subcommand(call)
}
`
}

func renderCLIDispatch(source model.CLIModel) string {
	var output strings.Builder
	output.WriteString(cliHeader(source))
	output.WriteString("use clap::ArgMatches;\nuse opendart::PrepareError;\n\nuse crate::prepared::{self, PreparedCall};\nuse super::catalog::operation;\n\npub(crate) fn prepare_call(matches: &ArgMatches) -> Result<PreparedCall, PrepareError> {\n    match matches.subcommand() {\n")
	for _, operation := range source.Operations {
		matchName := "matches"
		if len(operation.Parameters) == 0 && len(operation.Representations) == 1 {
			matchName = "_matches"
		}
		fmt.Fprintf(&output, "        Some((%s | %s, %s)) => {\n", quote(operation.Name), quote(operation.LogicalID), matchName)
		renderCLIOperationDispatch(&output, operation)
		output.WriteString("        }\n")
	}
	output.WriteString("        _ => unreachable!(\"clap requires one generated operation\"),\n    }\n}\n")
	return output.String()
}

func renderCLIOperationDispatch(output *strings.Builder, operation model.CLIOperation) {
	hasOptional := false
	var required []string
	for _, parameter := range operation.Parameters {
		if !parameter.Required {
			hasOptional = true
			continue
		}
		required = append(required, cliMatchExpression(parameter))
	}
	declaration := "let input"
	if hasOptional {
		declaration = "let mut input"
	}
	fmt.Fprintf(output, "            %s = opendart::operations::%s::new(%s);\n", declaration, operation.SDKInputType, strings.Join(required, ", "))
	for _, parameter := range operation.Parameters {
		if parameter.Required {
			continue
		}
		fmt.Fprintf(output, "            if let Some(value) = matches.%s(%s) { input = input.with_%s(%s); }\n",
			cliMatchGetter(parameter), quote(parameter.SDKField), parameter.SDKField, cliOptionalValue(parameter))
	}
	fmt.Fprintf(output, "            let operation = operation(%s).expect(\"generated catalog entry\");\n", quote(operation.Name))
	if len(operation.Representations) == 1 {
		representation := operation.Representations[0]
		fmt.Fprintf(output, "            %s\n", preparedExpression(representation))
		return
	}
	output.WriteString("            match matches.get_one::<String>(\"representation\").map(String::as_str) {\n")
	for _, representation := range operation.Representations {
		fmt.Fprintf(output, "                Some(%s) => %s,\n", quote(string(representation.Name)), preparedExpression(representation))
	}
	output.WriteString("                _ => unreachable!(\"clap validates representation\"),\n            }\n")
}

func cliMatchExpression(parameter model.CLIParameter) string {
	getter := cliMatchGetter(parameter)
	if parameter.Shape == model.StringArray {
		return fmt.Sprintf("matches.%s(%s).expect(\"clap requires input\").cloned().collect::<Vec<_>>()", getter, quote(parameter.SDKField))
	}
	return fmt.Sprintf("matches.%s(%s).expect(\"clap requires input\").clone()", getter, quote(parameter.SDKField))
}

func cliMatchGetter(parameter model.CLIParameter) string {
	if parameter.Shape == model.StringArray {
		return "get_many::<String>"
	}
	return "get_one::<String>"
}

func cliOptionalValue(parameter model.CLIParameter) string {
	if parameter.Shape == model.StringArray {
		return "value.cloned().collect::<Vec<_>>()"
	}
	return "value.clone()"
}

func preparedExpression(representation model.CLIRepresentation) string {
	constructor := "prepared::structured"
	if representation.Name == model.RepresentationZIP {
		return fmt.Sprintf("{ let request: opendart::PreparedBinaryRequest = input.%s()?; let _response_type: Option<%s> = None; Ok(prepared::binary(operation, request)) }", representation.PrepareMethod, representation.ResponseType)
	}
	return fmt.Sprintf("{ let request: opendart::PreparedRequest<%s> = input.%s()?; Ok(%s(operation, request)) }", representation.ResponseType, representation.PrepareMethod, constructor)
}

func rustIntOption(value *int64) string {
	if value == nil {
		return "None"
	}
	return fmt.Sprintf("Some(%d)", *value)
}

func rustStringOption(value string) string {
	if value == "" {
		return "None"
	}
	return "Some(" + quote(value) + ")"
}
