// Package rust emits formatter-stable Rust from the normalized SDK model.
package rust

import (
	"fmt"
	"net/url"
	"sort"
	"strconv"
	"strings"

	"github.com/cpaikr/opendart/internal/sdkgen/model"
)

const ownershipMarker = "opendart-sdk-generator-schema=1\n"

// Render returns the complete owned generated subtree keyed by slash-separated
// relative file name.
func Render(source model.Model) (map[string][]byte, error) {
	if source.SchemaVersion != model.SchemaVersion || source.Checksum == "" {
		return nil, fmt.Errorf("render Rust SDK: invalid model schema or checksum")
	}
	files := map[string][]byte{
		".opendart-sdk-generated": []byte(ownershipMarker),
		"mod.rs":                  []byte(renderModule(source)),
		"mapping.rs":              []byte(renderMapping(source)),
		"wire_shapes.rs":          []byte(renderWireShapes(source)),
	}
	groups := make(map[string][]model.LogicalOperation)
	for _, operation := range source.Logical {
		groups[operation.Group] = append(groups[operation.Group], operation)
	}
	groupNames := make([]string, 0, len(groups))
	for group := range groups {
		groupNames = append(groupNames, group)
	}
	sort.Strings(groupNames)
	files["operations/mod.rs"] = []byte(renderOperationsModule(source, groupNames))
	physical := make(map[string]model.PhysicalOperation, len(source.Physical))
	for _, operation := range source.Physical {
		physical[operation.OperationID] = operation
	}
	for _, group := range groupNames {
		files["operations/"+group+".rs"] = []byte(renderOperationGroup(source, groups[group], physical))
	}
	return files, nil
}

func header(source model.Model) string {
	return "// @generated by opendart-tool; DO NOT EDIT.\n" +
		fmt.Sprintf("// generator-schema: %d\n", source.SchemaVersion) +
		"// sdk-projection-sha256: " + source.Checksum + "\n\n"
}

func renderModule(source model.Model) string {
	return header(source) + fmt.Sprintf(
		"pub(crate) const GENERATOR_SCHEMA: u32 = %d;\npub(crate) const PROJECTION_CHECKSUM: &str = %s;\n\n/// Canonical public-name and identity mappings.\npub mod mapping;\n/// Generated logical-operation input types.\npub mod operations;\n/// Conservative response-routing shape metadata.\npub mod wire_shapes;\n",
		source.SchemaVersion, quote(source.Checksum),
	)
}

func renderMapping(source model.Model) string {
	var output strings.Builder
	output.WriteString(header(source))
	output.WriteString("/// Stable public-name mapping back to the canonical OpenAPI identities.\n")
	output.WriteString("#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]\npub struct OperationMapping {\n")
	output.WriteString("    /// Generated public Rust input type name.\n    pub rust_name: &'static str,\n    /// Canonical physical OpenAPI operation ID.\n    pub operation_id: &'static str,\n    /// Stable logical OpenDART operation ID.\n    pub logical_operation_id: &'static str,\n}\n\n")
	output.WriteString("/// Complete canonical physical-operation mapping.\npub const OPERATION_MAPPINGS: &[OperationMapping] = &[\n")
	logicalNames := make(map[string]string, len(source.Logical))
	for _, operation := range source.Logical {
		logicalNames[operation.ID] = operation.RustName
	}
	for _, operation := range source.Physical {
		fmt.Fprintf(&output, "    OperationMapping { rust_name: %s, operation_id: %s, logical_operation_id: %s },\n",
			quote(logicalNames[operation.LogicalID]), quote(operation.OperationID), quote(operation.LogicalID))
	}
	output.WriteString("];\n")
	return output.String()
}

func renderOperationsModule(source model.Model, groups []string) string {
	var output strings.Builder
	output.WriteString(header(source))
	for _, group := range groups {
		fmt.Fprintf(&output, "mod %s;\n", group)
	}
	output.WriteByte('\n')
	for _, group := range groups {
		fmt.Fprintf(&output, "pub use %s::*;\n", group)
	}
	return output.String()
}

func renderOperationGroup(source model.Model, operations []model.LogicalOperation, physical map[string]model.PhysicalOperation) string {
	var output strings.Builder
	output.WriteString(header(source))
	output.WriteString("use crate::request::{QueryParameter, QueryValue};\n")
	output.WriteString("use crate::{OperationIdentity, PrepareError, PreparedRequest, Representation};\n")
	output.WriteString("use super::super::{GENERATOR_SCHEMA, PROJECTION_CHECKSUM};\n\n")
	needed := make(map[string]bool)
	for _, operation := range operations {
		for _, variant := range operation.Variants {
			needed[expectedConstant(physical[variant.OperationID].ExpectedRepresentations)] = true
		}
	}
	if needed["JSON_ONLY"] {
		output.WriteString("const JSON_ONLY: &[Representation] = &[Representation::Json];\n")
	}
	if needed["XML_ONLY"] {
		output.WriteString("const XML_ONLY: &[Representation] = &[Representation::Xml];\n")
	}
	if needed["ZIP_OR_XML"] {
		output.WriteString("const ZIP_OR_XML: &[Representation] = &[Representation::Zip, Representation::Xml];\n")
	}
	output.WriteByte('\n')
	for _, operation := range operations {
		renderLogicalOperation(&output, operation, physical)
	}
	output.WriteString("fn require_nonempty(operation: OperationIdentity, parameter: &'static str, value: &str) -> Result<(), PrepareError> {\n")
	output.WriteString("    if value.is_empty() { return Err(PrepareError::MissingInput { operation, parameter }); }\n    Ok(())\n}\n")
	renderGeneratedRequestTests(&output, operations, physical)
	return output.String()
}

func renderGeneratedRequestTests(output *strings.Builder, operations []model.LogicalOperation, physical map[string]model.PhysicalOperation) {
	output.WriteString("\n#[cfg(test)]\nmod generated_request_tests {\n    use super::*;\n    use crate::{Authentication, RequestMethod};\n\n")
	output.WriteString("    #[test]\n    fn every_physical_request_matches_its_generated_vector() {\n")
	for _, operation := range operations {
		for _, variant := range operation.Variants {
			physicalOperation := physical[variant.OperationID]
			output.WriteString("        {\n")
			fmt.Fprintf(output, "            let input = %s;\n", inputExpression(operation, true))
			fmt.Fprintf(output, "            let prepared = input.prepare(Representation::%s).expect(\"generated vector must prepare\");\n", rustRepresentation(variant.Representation))
			fmt.Fprintf(output, "            assert_eq!(prepared.identity().physical(), %s);\n", quote(physicalOperation.OperationID))
			fmt.Fprintf(output, "            assert_eq!(prepared.identity().logical(), %s);\n", quote(physicalOperation.LogicalID))
			output.WriteString("            assert_eq!(prepared.method(), RequestMethod::Get);\n")
			fmt.Fprintf(output, "            assert_eq!(prepared.relative_path(), %s);\n", quote(physicalOperation.Path))
			fmt.Fprintf(output, "            assert_eq!(prepared.encoded_query(), %s);\n", quote(vectorQuery(operation.Parameters, true)))
			output.WriteString("            assert_eq!(prepared.authentication(), Authentication::ApiKeyQuery);\n")
			output.WriteString("            assert!(!prepared.encoded_query().contains(\"crtfc_key\"));\n")
			fmt.Fprintf(output, "            assert_eq!(prepared.expected_representations(), %s);\n", expectedConstant(physicalOperation.ExpectedRepresentations))
			output.WriteString("            assert_eq!(prepared.generator_schema(), GENERATOR_SCHEMA);\n")
			output.WriteString("            assert_eq!(prepared.projection_identity(), PROJECTION_CHECKSUM);\n")
			if hasOptionalParameter(operation.Parameters) {
				fmt.Fprintf(output, "            let defaults = %s.prepare(Representation::%s).expect(\"omitted optional values must prepare\");\n", inputExpression(operation, false), rustRepresentation(variant.Representation))
				fmt.Fprintf(output, "            assert_eq!(defaults.encoded_query(), %s);\n", quote(vectorQuery(operation.Parameters, false)))
			}
			output.WriteString("        }\n")
		}
	}
	output.WriteString("    }\n}\n")
}

func constructorArguments(parameters []model.Parameter) string {
	var arguments []string
	for _, parameter := range parameters {
		if !parameter.Required {
			continue
		}
		if parameter.Shape == model.StringArray {
			arguments = append(arguments, "[\"first,value\", \"회사 /+\"]")
		} else {
			arguments = append(arguments, "\"value /+\"")
		}
	}
	return strings.Join(arguments, ", ")
}

func inputExpression(operation model.LogicalOperation, includeOptional bool) string {
	result := operation.RustName + "::new(" + constructorArguments(operation.Parameters) + ")"
	if !includeOptional {
		return result
	}
	for _, parameter := range operation.Parameters {
		if parameter.Required {
			continue
		}
		value := "\"value /+\""
		if parameter.Shape == model.StringArray {
			value = "[\"first,value\", \"회사 /+\"]"
		}
		result += ".with_" + parameter.RustName + "(" + value + ")"
	}
	return result
}

func vectorQuery(parameters []model.Parameter, includeOptional bool) string {
	var pairs []string
	for _, parameter := range parameters {
		if !parameter.Required && !includeOptional {
			continue
		}
		value := url.QueryEscape("value /+")
		if parameter.Shape == model.StringArray {
			value = url.QueryEscape("first,value") + "," + url.QueryEscape("회사 /+")
		}
		pairs = append(pairs, parameter.WireName+"="+value)
	}
	return strings.Join(pairs, "&")
}

func renderLogicalOperation(output *strings.Builder, operation model.LogicalOperation, physical map[string]model.PhysicalOperation) {
	fmt.Fprintf(output, "/// OpenDART logical operation `%s` (API ID `%s`).\n///\n/// Source: <%s>\n", operation.ID, operation.APIID, operation.GuideURL)
	if len(operation.Parameters) == 0 {
		fmt.Fprintf(output, "#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]\npub struct %s;\n\n", operation.RustName)
	} else {
		deriveDefault := ""
		if !hasRequiredParameter(operation.Parameters) {
			deriveDefault = "Default, "
		}
		fmt.Fprintf(output, "#[derive(Clone, Debug, %sEq, PartialEq)]\npub struct %s {\n", deriveDefault, operation.RustName)
		for _, parameter := range operation.Parameters {
			fmt.Fprintf(output, "    %s: %s,\n", parameter.RustName, rustParameterType(parameter))
		}
		output.WriteString("}\n\n")
	}
	fmt.Fprintf(output, "impl %s {\n", operation.RustName)
	fmt.Fprintf(output, "    const LOGICAL_OPERATION_ID: &'static str = %s;\n\n", quote(operation.ID))
	renderConstructor(output, operation)
	for _, parameter := range operation.Parameters {
		renderParameterMethods(output, parameter)
	}
	output.WriteString("    /// Prepares one physical representation without performing I/O.\n")
	output.WriteString("    pub fn prepare(&self, representation: Representation) -> Result<PreparedRequest, PrepareError> {\n")
	output.WriteString("        let (path, identity, expected) = match representation {\n")
	for _, variant := range operation.Variants {
		physicalOperation := physical[variant.OperationID]
		fmt.Fprintf(output, "            Representation::%s => (%s, OperationIdentity::new(%s, Self::LOGICAL_OPERATION_ID), %s),\n",
			rustRepresentation(variant.Representation), quote(physicalOperation.Path), quote(variant.OperationID), expectedConstant(physicalOperation.ExpectedRepresentations))
	}
	output.WriteString("            _ => return Err(PrepareError::UnsupportedRepresentation { logical_operation: Self::LOGICAL_OPERATION_ID, representation }),\n")
	output.WriteString("        };\n")
	for _, parameter := range operation.Parameters {
		if parameter.Required && parameter.Shape == model.ScalarString {
			fmt.Fprintf(output, "        require_nonempty(identity, %s, &self.%s)?;\n", quote(parameter.WireName), parameter.RustName)
		}
		if !parameter.Required && parameter.Shape == model.ScalarString {
			fmt.Fprintf(output, "        if let Some(value) = &self.%s { require_nonempty(identity, %s, value)?; }\n", parameter.RustName, quote(parameter.WireName))
		}
		if parameter.Shape == model.StringArray {
			renderCardinalityCheck(output, parameter)
		}
	}
	if len(operation.Parameters) == 0 {
		output.WriteString("        let parameters = [];\n")
	} else if !hasOptionalParameter(operation.Parameters) {
		output.WriteString("        let parameters = vec![\n")
		for _, parameter := range operation.Parameters {
			fmt.Fprintf(output, "            QueryParameter { name: %s, value: %s },\n", quote(parameter.WireName), queryValue(parameter, requiredParameterReference(parameter)))
		}
		output.WriteString("        ];\n")
	} else {
		fmt.Fprintf(output, "        let mut parameters = Vec::with_capacity(%d);\n", len(operation.Parameters))
		for _, parameter := range operation.Parameters {
			renderQueryParameter(output, parameter)
		}
	}
	output.WriteString("        Ok(PreparedRequest::new(path, identity, &parameters, expected, GENERATOR_SCHEMA, PROJECTION_CHECKSUM))\n")
	output.WriteString("    }\n}\n\n")
}

func renderConstructor(output *strings.Builder, operation model.LogicalOperation) {
	required := make([]model.Parameter, 0, len(operation.Parameters))
	for _, parameter := range operation.Parameters {
		if parameter.Required {
			required = append(required, parameter)
		}
	}
	if len(operation.Parameters) == 0 {
		output.WriteString("    /// Creates the parameter-free operation input.\n    #[must_use]\n    pub const fn new() -> Self { Self }\n\n")
		return
	}
	output.WriteString("    /// Creates an operation input. Explicit contract validation occurs during preparation.\n")
	output.WriteString("    #[must_use]\n")
	if len(required) == 0 {
		output.WriteString("    pub fn new() -> Self {\n")
	} else {
		output.WriteString("    pub fn new(")
		for index, parameter := range required {
			if index > 0 {
				output.WriteString(", ")
			}
			fmt.Fprintf(output, "%s: %s", parameter.RustName, constructorType(parameter))
		}
		output.WriteString(") -> Self {\n")
	}
	output.WriteString("        Self {\n")
	for _, parameter := range operation.Parameters {
		if !parameter.Required {
			fmt.Fprintf(output, "            %s: None,\n", parameter.RustName)
		} else if parameter.Shape == model.StringArray {
			fmt.Fprintf(output, "            %s: %s.into_iter().map(Into::into).collect(),\n", parameter.RustName, parameter.RustName)
		} else {
			fmt.Fprintf(output, "            %s: %s.into(),\n", parameter.RustName, parameter.RustName)
		}
	}
	output.WriteString("        }\n    }\n\n")
}

func renderParameterMethods(output *strings.Builder, parameter model.Parameter) {
	if parameter.Required {
		fmt.Fprintf(output, "    /// Returns the `%s` input.\n    #[must_use]\n    pub fn %s(&self) -> %s { %s }\n\n",
			parameter.WireName, parameter.RustName, getterType(parameter), getterExpression(parameter))
		return
	}
	fmt.Fprintf(output, "    /// Sets the optional `%s` input.\n    #[must_use]\n    pub fn with_%s(mut self, value: %s) -> Self { self.%s = Some(%s); self }\n\n",
		parameter.WireName, parameter.RustName, constructorType(parameter), parameter.RustName, ownedConversion(parameter, "value"))
	fmt.Fprintf(output, "    /// Returns the optional `%s` input when supplied.\n    #[must_use]\n    pub fn %s(&self) -> %s { %s }\n\n",
		parameter.WireName, parameter.RustName, getterType(parameter), getterExpression(parameter))
}

func renderCardinalityCheck(output *strings.Builder, parameter model.Parameter) {
	minimum, maximum := *parameter.MinItems, *parameter.MaxItems
	if parameter.Required {
		fmt.Fprintf(output, "        if !(%d..=%d).contains(&self.%s.len()) { return Err(PrepareError::InvalidCardinality { operation: identity, parameter: %s, minimum: %d, maximum: %d }); }\n",
			minimum, maximum, parameter.RustName, quote(parameter.WireName), minimum, maximum)
		return
	}
	fmt.Fprintf(output, "        if let Some(value) = &self.%s { if !(%d..=%d).contains(&value.len()) { return Err(PrepareError::InvalidCardinality { operation: identity, parameter: %s, minimum: %d, maximum: %d }); } }\n",
		parameter.RustName, minimum, maximum, quote(parameter.WireName), minimum, maximum)
}

func renderQueryParameter(output *strings.Builder, parameter model.Parameter) {
	if parameter.Required {
		fmt.Fprintf(output, "        parameters.push(QueryParameter { name: %s, value: %s });\n", quote(parameter.WireName), queryValue(parameter, requiredParameterReference(parameter)))
		return
	}
	fmt.Fprintf(output, "        if let Some(value) = &self.%s { parameters.push(QueryParameter { name: %s, value: %s }); }\n",
		parameter.RustName, quote(parameter.WireName), queryValue(parameter, "value"))
}

func hasRequiredParameter(parameters []model.Parameter) bool {
	for _, parameter := range parameters {
		if parameter.Required {
			return true
		}
	}
	return false
}

func hasOptionalParameter(parameters []model.Parameter) bool {
	for _, parameter := range parameters {
		if !parameter.Required {
			return true
		}
	}
	return false
}

func requiredParameterReference(parameter model.Parameter) string {
	if parameter.Shape == model.ScalarString {
		return "self." + parameter.RustName + ".as_str()"
	}
	return "&self." + parameter.RustName
}

func queryValue(parameter model.Parameter, reference string) string {
	if parameter.Shape == model.StringArray {
		return "QueryValue::CommaSeparated(" + reference + ")"
	}
	return "QueryValue::Scalar(" + reference + ")"
}

func renderWireShapes(source model.Model) string {
	var output strings.Builder
	output.WriteString(header(source))
	output.WriteString("/// Conservative kind established by the canonical source schema.\n#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]\n")
	output.WriteString("pub enum WireShapeKind {\n    /// An object with named properties.\n    Object,\n    /// An ordered array.\n    Array,\n    /// A source-established string.\n    String,\n    /// A scalar whose type is not established.\n    Opaque,\n    /// Uninterpreted binary entity bytes.\n    Binary,\n}\n\n")
	output.WriteString("/// Source policy for fields not named by an object schema.\n#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]\n")
	output.WriteString("pub enum AdditionalPropertiesPolicy {\n    /// The canonical schema does not close or explicitly open the object.\n    Unspecified,\n    /// Additional properties are explicitly allowed.\n    Allowed,\n    /// Additional properties are explicitly forbidden.\n    Forbidden,\n}\n\n")
	output.WriteString("/// One flattened node in a conservative response-shape tree.\n#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]\npub struct WireShapeNode {\n")
	output.WriteString("    /// Stable source-field path from the media root.\n    pub path: &'static str,\n    /// Selected canonical source description, or an empty string when absent.\n    pub description: &'static str,\n    /// Conservative source-established value kind.\n    pub kind: WireShapeKind,\n    /// Whether the parent object requires this property.\n    pub required: bool,\n    /// Additional-property policy when this node is an object.\n    pub additional_properties: AdditionalPropertiesPolicy,\n    /// OpenAPI XML element name, or an empty string when unspecified.\n    pub xml_name: &'static str,\n    /// OpenAPI 3.2 XML node type, or an empty string when unspecified.\n    pub xml_node_type: &'static str,\n    /// Documented values when this is the open OpenDART status field.\n    pub known_statuses: &'static [&'static str],\n}\n\n")
	output.WriteString("/// Response routing and conservative wire-shape metadata for one media type.\n#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]\npub struct ResponseShape {\n")
	output.WriteString("    /// Canonical physical OpenAPI operation ID.\n    pub operation_id: &'static str,\n    /// OpenAPI response selector such as `default`.\n    pub selector: &'static str,\n    /// Canonical evidence for interpreting the HTTP response status.\n    pub http_status_evidence: &'static str,\n    /// Declared response media type.\n    pub media_type: &'static str,\n    /// Canonical evidence classification for the content type.\n    pub content_type_status: &'static str,\n    /// Flattened conservative shape tree.\n    pub nodes: &'static [WireShapeNode],\n}\n\n")
	for _, operation := range source.Physical {
		for responseIndex, response := range operation.Responses {
			for mediaIndex, media := range response.Media {
				name := fmt.Sprintf("%s_RESPONSE_%d_MEDIA_%d", operation.RustConstant, responseIndex, mediaIndex)
				fmt.Fprintf(&output, "const %s: &[WireShapeNode] = &[\n", name)
				var nodes []flatShape
				flattenShape("$", true, media.Shape, &nodes)
				for _, node := range nodes {
					fmt.Fprintf(&output, "    WireShapeNode { path: %s, description: %s, kind: WireShapeKind::%s, required: %t, additional_properties: AdditionalPropertiesPolicy::%s, xml_name: %s, xml_node_type: %s, known_statuses: %s },\n",
						quote(node.path), quote(node.shape.Description), rustShapeKind(node.shape.Kind), node.required, rustAdditionalPolicy(node.shape.AdditionalPropertiesPolicy), quote(node.shape.XMLName), quote(node.shape.XMLNodeType), rustStringSlice(node.shape.StatusValues))
				}
				output.WriteString("];\n")
			}
		}
	}
	output.WriteString("\n/// Complete generated response-routing inventory.\npub const RESPONSE_SHAPES: &[ResponseShape] = &[\n")
	for _, operation := range source.Physical {
		for responseIndex, response := range operation.Responses {
			for mediaIndex, media := range response.Media {
				name := fmt.Sprintf("%s_RESPONSE_%d_MEDIA_%d", operation.RustConstant, responseIndex, mediaIndex)
				fmt.Fprintf(&output, "    ResponseShape { operation_id: %s, selector: %s, http_status_evidence: %s, media_type: %s, content_type_status: %s, nodes: %s },\n",
					quote(operation.OperationID), quote(response.Selector), quote(response.HTTPStatusEvidence), quote(media.Name), quote(media.ContentTypeStatus), name)
			}
		}
	}
	output.WriteString("];\n")
	return output.String()
}

type flatShape struct {
	path     string
	required bool
	shape    model.ResponseShape
}

func flattenShape(path string, required bool, shape model.ResponseShape, output *[]flatShape) {
	*output = append(*output, flatShape{path: path, required: required, shape: shape})
	requiredNames := make(map[string]bool, len(shape.Required))
	for _, name := range shape.Required {
		requiredNames[name] = true
	}
	for _, property := range shape.Properties {
		flattenShape(path+"."+property.Name, requiredNames[property.Name], property.Shape, output)
	}
	if shape.Items != nil {
		flattenShape(path+"[]", true, *shape.Items, output)
	}
}

func rustParameterType(parameter model.Parameter) string {
	base := "String"
	if parameter.Shape == model.StringArray {
		base = "Vec<String>"
	}
	if !parameter.Required {
		return "Option<" + base + ">"
	}
	return base
}

func constructorType(parameter model.Parameter) string {
	if parameter.Shape == model.StringArray {
		return "impl IntoIterator<Item = impl Into<String>>"
	}
	return "impl Into<String>"
}

func getterType(parameter model.Parameter) string {
	if parameter.Required {
		if parameter.Shape == model.StringArray {
			return "&[String]"
		}
		return "&str"
	}
	if parameter.Shape == model.StringArray {
		return "Option<&[String]>"
	}
	return "Option<&str>"
}

func getterExpression(parameter model.Parameter) string {
	if parameter.Required {
		if parameter.Shape == model.StringArray {
			return "&self." + parameter.RustName
		}
		return "&self." + parameter.RustName
	}
	if parameter.Shape == model.StringArray {
		return "self." + parameter.RustName + ".as_deref()"
	}
	return "self." + parameter.RustName + ".as_deref()"
}

func ownedConversion(parameter model.Parameter, value string) string {
	if parameter.Shape == model.StringArray {
		return value + ".into_iter().map(Into::into).collect()"
	}
	return value + ".into()"
}

func expectedConstant(representations []model.Representation) string {
	if len(representations) == 1 && representations[0] == model.RepresentationJSON {
		return "JSON_ONLY"
	}
	if len(representations) == 1 && representations[0] == model.RepresentationXML {
		return "XML_ONLY"
	}
	if len(representations) == 2 && representations[0] == model.RepresentationZIP && representations[1] == model.RepresentationXML {
		return "ZIP_OR_XML"
	}
	panic(fmt.Sprintf("unsupported normalized representation set: %#v", representations))
}

func rustRepresentation(value model.Representation) string {
	switch value {
	case model.RepresentationJSON:
		return "Json"
	case model.RepresentationXML:
		return "Xml"
	case model.RepresentationZIP:
		return "Zip"
	default:
		panic("unsupported normalized representation")
	}
}

func rustShapeKind(value string) string {
	switch value {
	case "object":
		return "Object"
	case "array":
		return "Array"
	case "string":
		return "String"
	case "opaque":
		return "Opaque"
	case "binary":
		return "Binary"
	default:
		panic("unsupported normalized shape")
	}
}

func rustAdditionalPolicy(value string) string {
	switch value {
	case "unspecified":
		return "Unspecified"
	case "allowed":
		return "Allowed"
	case "forbidden":
		return "Forbidden"
	default:
		panic("unsupported additional-properties policy")
	}
}

func rustStringSlice(values []string) string {
	if len(values) == 0 {
		return "&[]"
	}
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, quote(value))
	}
	return "&[" + strings.Join(quoted, ", ") + "]"
}

func quote(value string) string {
	return strconv.Quote(value)
}
