// Package rust emits deterministically formatted Rust from the normalized SDK model.
package rust

import (
	"fmt"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"unicode"

	"github.com/cpaikr/opendart/internal/sdkgen/model"
	"github.com/cpaikr/opendart/internal/sdkgen/ownership"
)

// Render returns the complete owned generated subtree keyed by slash-separated
// relative file name.
func Render(source model.Model) (map[string][]byte, error) {
	if source.SchemaVersion != model.SchemaVersion || source.Checksum == "" {
		return nil, fmt.Errorf("render Rust SDK: invalid model schema or checksum")
	}
	if err := validateRustSymbols(source); err != nil {
		return nil, err
	}
	if err := validateXMLRoots(source); err != nil {
		return nil, err
	}
	files := map[string][]byte{
		ownership.Filename: []byte(ownership.Marker(source.SchemaVersion)),
		"mod.rs":           []byte(renderModule(source)),
		"mapping.rs":       []byte(renderMapping(source)),
	}
	groups := make(map[string][]model.LogicalOperation)
	for _, operation := range source.Logical {
		groups[operation.Group] = append(groups[operation.Group], operation)
	}
	groupNames := make([]string, 0, len(groups))
	for group := range groups {
		groupNames = append(groupNames, group)
	}
	sort.Strings(groupNames)
	files["operations/mod.rs"] = []byte(renderOperationsModule(source, groupNames))
	files["responses/mod.rs"] = []byte(renderResponsesModule(source, groupNames))
	physical := make(map[string]model.PhysicalOperation, len(source.Physical))
	for _, operation := range source.Physical {
		physical[operation.OperationID] = operation
	}
	for _, group := range groupNames {
		files["operations/"+group+".rs"] = []byte(renderOperationGroup(source, groups[group], physical))
		responses, err := renderResponseGroup(source, groups[group], physical)
		if err != nil {
			return nil, err
		}
		files["responses/"+group+".rs"] = []byte(responses)
	}
	return files, nil
}

func header(source model.Model) string {
	return "// @generated by opendart-tool; DO NOT EDIT.\n" +
		fmt.Sprintf("// generator-schema: %d\n", source.SchemaVersion) +
		"// sdk-projection-sha256: " + source.Checksum + "\n\n"
}

func renderModule(source model.Model) string {
	return header(source) + fmt.Sprintf(
		"pub(crate) const GENERATOR_SCHEMA: u32 = %d;\npub(crate) const PROJECTION_CHECKSUM: &str = %s;\n\n/// Generator-owned logical-operation input types.\n///\n/// Types in this module are supported public API. The generated file layout is not.\npub mod operations;\n/// Generator-owned representation-specific response wire types.\n///\n/// Types in this module are supported public API. The generated file layout is not.\npub mod responses;\n#[cfg(test)]\npub(crate) mod mapping;\n\n#[cfg(test)]\nmod generated_inventory_tests {\n    use std::collections::{BTreeMap, BTreeSet};\n\n    use super::mapping::OPERATION_MAPPINGS;\n\n    #[test]\n    fn mappings_cover_the_physical_inventory_without_public_name_drift() {\n        let mut physical = BTreeSet::new();\n        let mut logical_names = BTreeMap::new();\n        for mapping in OPERATION_MAPPINGS {\n            assert!(physical.insert(mapping.operation_id), \"duplicate physical mapping: {}\", mapping.operation_id);\n            if let Some(previous) = logical_names.insert(mapping.logical_operation_id, mapping.rust_name) {\n                assert_eq!(previous, mapping.rust_name, \"logical operation has multiple public names: {}\", mapping.logical_operation_id);\n            }\n        }\n        assert!(!physical.is_empty());\n    }\n}\n",
		source.SchemaVersion, quote(source.Checksum),
	)
}

func renderMapping(source model.Model) string {
	var output strings.Builder
	output.WriteString(header(source))
	output.WriteString("/// Stable public-name mapping back to the canonical OpenAPI identities.\n")
	output.WriteString("#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]\npub(crate) struct OperationMapping {\n")
	output.WriteString("    /// Generated public Rust input type name.\n    pub rust_name: &'static str,\n    /// Canonical physical OpenAPI operation ID.\n    pub operation_id: &'static str,\n    /// Stable logical OpenDART operation ID.\n    pub logical_operation_id: &'static str,\n}\n\n")
	output.WriteString("/// Complete canonical physical-operation mapping.\npub(crate) const OPERATION_MAPPINGS: &[OperationMapping] = &[\n")
	logicalNames := make(map[string]string, len(source.Logical))
	for _, operation := range source.Logical {
		logicalNames[operation.ID] = operation.RustName
	}
	for _, operation := range source.Physical {
		fmt.Fprintf(&output, "    OperationMapping { rust_name: %s, operation_id: %s, logical_operation_id: %s },\n",
			quote(logicalNames[operation.LogicalID]), quote(operation.OperationID), quote(operation.LogicalID))
	}
	output.WriteString("];\n")
	return output.String()
}

func renderOperationsModule(source model.Model, groups []string) string {
	var output strings.Builder
	output.WriteString(header(source))
	for _, group := range groups {
		fmt.Fprintf(&output, "mod %s;\n", group)
	}
	output.WriteByte('\n')
	for _, group := range groups {
		fmt.Fprintf(&output, "pub use %s::*;\n", group)
	}
	return output.String()
}

func renderResponsesModule(source model.Model, groups []string) string {
	var output strings.Builder
	output.WriteString(header(source))
	for _, group := range groups {
		fmt.Fprintf(&output, "pub(crate) mod %s;\n", group)
	}
	output.WriteByte('\n')
	for _, group := range groups {
		fmt.Fprintf(&output, "pub use %s::*;\n", group)
	}
	return output.String()
}

func renderOperationGroup(source model.Model, operations []model.LogicalOperation, physical map[string]model.PhysicalOperation) string {
	var output strings.Builder
	output.WriteString(header(source))
	output.WriteString("use crate::request::{QueryParameter, QueryValue, RequestParts};\n")
	requestImports := []string{"OperationIdentity", "PrepareError"}
	if hasBinaryVariant(operations) {
		requestImports = append(requestImports, "PreparedBinaryRequest")
	}
	if hasStructuredVariant(operations) {
		requestImports = append(requestImports, "PreparedRequest")
	}
	requestImports = append(requestImports, "Representation")
	fmt.Fprintf(&output, "use crate::{%s};\n", strings.Join(requestImports, ", "))
	if validationImports := operationValidationImports(operations); len(validationImports) > 0 {
		fmt.Fprintf(&output, "use crate::validation::{%s};\n", strings.Join(validationImports, ", "))
	}
	fmt.Fprintf(&output, "use super::super::responses::%s as response;\n", operations[0].Group)
	output.WriteString("use super::super::{GENERATOR_SCHEMA, PROJECTION_CHECKSUM};\n\n")
	needed := make(map[string]bool)
	for _, operation := range operations {
		for _, variant := range operation.Variants {
			needed[expectedConstant(physical[variant.OperationID].ExpectedRepresentations)] = true
		}
	}
	if needed["JSON_ONLY"] {
		output.WriteString("const JSON_ONLY: &[Representation] = &[Representation::Json];\n")
	}
	if needed["XML_ONLY"] {
		output.WriteString("const XML_ONLY: &[Representation] = &[Representation::Xml];\n")
	}
	if needed["ZIP_OR_XML"] {
		output.WriteString("const ZIP_OR_XML: &[Representation] = &[Representation::Zip, Representation::Xml];\n")
	}
	output.WriteByte('\n')
	for _, operation := range operations {
		renderLogicalOperation(&output, operation, physical)
	}
	output.WriteString("fn require_nonempty(operation: OperationIdentity, parameter: &'static str, value: &str) -> Result<(), PrepareError> {\n")
	output.WriteString("    if value.is_empty() { return Err(PrepareError::MissingInput { operation, parameter }); }\n    Ok(())\n}\n")
	renderGeneratedRequestTests(&output, operations, physical)
	return output.String()
}

func renderGeneratedRequestTests(output *strings.Builder, operations []model.LogicalOperation, physical map[string]model.PhysicalOperation) {
	output.WriteString("\n#[cfg(test)]\nmod generated_request_tests {\n    use super::*;\n    use crate::{Authentication, RequestMethod};\n\n")
	output.WriteString("    #[test]\n    fn every_physical_request_matches_its_generated_vector() {\n")
	for _, operation := range operations {
		for _, variant := range operation.Variants {
			physicalOperation := physical[variant.OperationID]
			output.WriteString("        {\n")
			fmt.Fprintf(output, "            let input = %s;\n", inputExpression(operation, true))
			fmt.Fprintf(output, "            let prepared = input.%s().expect(\"generated vector must prepare\");\n", preparationMethod(variant.Representation))
			fmt.Fprintf(output, "            assert_eq!(prepared.identity().physical(), %s);\n", quote(physicalOperation.OperationID))
			fmt.Fprintf(output, "            assert_eq!(prepared.identity().logical(), %s);\n", quote(physicalOperation.LogicalID))
			output.WriteString("            assert_eq!(prepared.method(), RequestMethod::Get);\n")
			fmt.Fprintf(output, "            assert_eq!(prepared.relative_path(), %s);\n", quote(physicalOperation.Path))
			fmt.Fprintf(output, "            assert_eq!(prepared.encoded_query(), %s);\n", quote(vectorQuery(operation.Parameters, true)))
			output.WriteString("            assert_eq!(prepared.authentication(), Authentication::ApiKeyQuery);\n")
			output.WriteString("            assert!(!prepared.encoded_query().contains(\"crtfc_key\"));\n")
			fmt.Fprintf(output, "            assert_eq!(prepared.expected_representations(), %s);\n", expectedConstant(physicalOperation.ExpectedRepresentations))
			output.WriteString("            assert_eq!(prepared.generator_schema(), GENERATOR_SCHEMA);\n")
			output.WriteString("            assert_eq!(prepared.projection_identity(), PROJECTION_CHECKSUM);\n")
			if hasOptionalParameter(operation.Parameters) {
				fmt.Fprintf(output, "            let defaults = %s.%s().expect(\"omitted optional values must prepare\");\n", inputExpression(operation, false), preparationMethod(variant.Representation))
				fmt.Fprintf(output, "            assert_eq!(defaults.encoded_query(), %s);\n", quote(vectorQuery(operation.Parameters, false)))
			}
			output.WriteString("        }\n")
		}
	}
	output.WriteString("    }\n}\n")
}

func constructorArguments(parameters []model.Parameter) string {
	var arguments []string
	for _, parameter := range parameters {
		if !parameter.Required {
			continue
		}
		if parameter.Shape == model.StringArray {
			arguments = append(arguments, rustArraySample(parameter))
		} else {
			arguments = append(arguments, quote(stringSample(parameter)))
		}
	}
	return strings.Join(arguments, ", ")
}

func inputExpression(operation model.LogicalOperation, includeOptional bool) string {
	result := operation.RustName + "::new(" + constructorArguments(operation.Parameters) + ")"
	if !includeOptional {
		return result
	}
	for _, parameter := range operation.Parameters {
		if parameter.Required {
			continue
		}
		value := quote(stringSample(parameter))
		if parameter.Shape == model.StringArray {
			value = rustArraySample(parameter)
		}
		result += ".with_" + parameter.RustName + "(" + value + ")"
	}
	return result
}

func vectorQuery(parameters []model.Parameter, includeOptional bool) string {
	var pairs []string
	for _, parameter := range parameters {
		if !parameter.Required && !includeOptional {
			continue
		}
		value := url.QueryEscape(stringSample(parameter))
		if parameter.Shape == model.StringArray {
			values := arraySamples(parameter)
			value = url.QueryEscape(values[0]) + "," + url.QueryEscape(values[1])
		}
		pairs = append(pairs, parameter.WireName+"="+value)
	}
	return strings.Join(pairs, "&")
}

func stringSample(parameter model.Parameter) string {
	constraints := parameter.Constraints
	if len(constraints.AllowedValues) > 0 {
		return constraints.AllowedValues[0]
	}
	switch constraints.Format {
	case "opendart-corp-code":
		return "00126380"
	case "opendart-date":
		return "20240229"
	case "opendart-year":
		return "2024"
	}
	if constraints.DecimalMinimum != nil {
		return fmt.Sprint(*constraints.DecimalMinimum)
	}
	return "value /+"
}

func arraySamples(parameter model.Parameter) [2]string {
	if parameter.Constraints.Format == "opendart-corp-code" {
		return [2]string{"00126380", "00164779"}
	}
	return [2]string{stringSample(parameter), stringSample(parameter)}
}

func rustArraySample(parameter model.Parameter) string {
	values := arraySamples(parameter)
	return "[" + quote(values[0]) + ", " + quote(values[1]) + "]"
}

func renderLogicalOperation(output *strings.Builder, operation model.LogicalOperation, physical map[string]model.PhysicalOperation) {
	fmt.Fprintf(output, "/// OpenDART logical operation `%s` (API ID `%s`).\n///\n/// Source: <%s>\n", operation.ID, operation.APIID, operation.GuideURL)
	if len(operation.Parameters) == 0 {
		fmt.Fprintf(output, "#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]\npub struct %s;\n\n", operation.RustName)
	} else {
		deriveDefault := ""
		if !hasRequiredParameter(operation.Parameters) {
			deriveDefault = "Default, "
		}
		fmt.Fprintf(output, "#[derive(Clone, Debug, %sEq, PartialEq)]\npub struct %s {\n", deriveDefault, operation.RustName)
		for _, parameter := range operation.Parameters {
			fmt.Fprintf(output, "    %s: %s,\n", parameter.RustName, rustParameterType(parameter))
		}
		output.WriteString("}\n\n")
	}
	fmt.Fprintf(output, "impl %s {\n", operation.RustName)
	fmt.Fprintf(output, "    const LOGICAL_OPERATION_ID: &'static str = %s;\n\n", quote(operation.ID))
	renderConstructor(output, operation)
	for _, parameter := range operation.Parameters {
		renderParameterMethods(output, parameter)
	}
	for _, variant := range operation.Variants {
		physicalOperation := physical[variant.OperationID]
		xmlRoot := expectedXMLRoot(physicalOperation)
		method := preparationMethod(variant.Representation)
		fmt.Fprintf(output, "    /// Prepares the %s physical representation without performing I/O.\n", strings.ToUpper(string(variant.Representation)))
		if variant.Representation == model.RepresentationZIP {
			fmt.Fprintf(output, "    pub fn %s(&self) -> Result<PreparedBinaryRequest, PrepareError> {\n", method)
			fmt.Fprintf(output, "        let identity = OperationIdentity::new(%s, Self::LOGICAL_OPERATION_ID);\n", quote(variant.OperationID))
			fmt.Fprintf(output, "        let parts = self.prepare_parts(%s, identity, %s, %s)?;\n", quote(physicalOperation.Path), expectedConstant(physicalOperation.ExpectedRepresentations), rustOption(xmlRoot))
			output.WriteString("        Ok(PreparedBinaryRequest::new(parts))\n")
		} else {
			responseName := responseRootName(operation.RustName, variant.Representation)
			fmt.Fprintf(output, "    pub fn %s(&self) -> Result<PreparedRequest<response::%s>, PrepareError> {\n", method, responseName)
			fmt.Fprintf(output, "        let identity = OperationIdentity::new(%s, Self::LOGICAL_OPERATION_ID);\n", quote(variant.OperationID))
			fmt.Fprintf(output, "        let parts = self.prepare_parts(%s, identity, %s, %s)?;\n", quote(physicalOperation.Path), expectedConstant(physicalOperation.ExpectedRepresentations), rustOption(xmlRoot))
			fmt.Fprintf(output, "        Ok(PreparedRequest::new(parts, response::%s))\n", responseDecoderName(responseName))
		}
		output.WriteString("    }\n\n")
	}
	output.WriteString("    fn prepare_parts(&self, path: &'static str, identity: OperationIdentity, expected: &'static [Representation], expected_xml_root: Option<&'static str>) -> Result<RequestParts, PrepareError> {\n")
	for _, parameter := range operation.Parameters {
		if parameter.Required && parameter.Shape == model.ScalarString {
			fmt.Fprintf(output, "        require_nonempty(identity, %s, &self.%s)?;\n", quote(parameter.WireName), parameter.RustName)
			renderStringConstraintChecks(output, parameter, "&self."+parameter.RustName, "        ")
		}
		if !parameter.Required && parameter.Shape == model.ScalarString {
			fmt.Fprintf(output, "        if let Some(value) = &self.%s {\n            require_nonempty(identity, %s, value)?;\n", parameter.RustName, quote(parameter.WireName))
			renderStringConstraintChecks(output, parameter, "value", "            ")
			output.WriteString("        }\n")
		}
		if parameter.Shape == model.StringArray {
			renderCardinalityCheck(output, parameter)
			renderArrayElementCheck(output, parameter)
		}
	}
	if len(operation.Parameters) == 0 {
		output.WriteString("        let parameters = [];\n")
	} else if !hasOptionalParameter(operation.Parameters) {
		output.WriteString("        let parameters = vec![\n")
		for _, parameter := range operation.Parameters {
			fmt.Fprintf(output, "            QueryParameter { name: %s, value: %s },\n", quote(parameter.WireName), queryValue(parameter, requiredParameterReference(parameter)))
		}
		output.WriteString("        ];\n")
	} else {
		fmt.Fprintf(output, "        let mut parameters = Vec::with_capacity(%d);\n", len(operation.Parameters))
		for _, parameter := range operation.Parameters {
			renderQueryParameter(output, parameter)
		}
	}
	output.WriteString("        Ok(RequestParts::new(path, identity, &parameters, expected, expected_xml_root, GENERATOR_SCHEMA, PROJECTION_CHECKSUM))\n")
	output.WriteString("    }\n}\n\n")
}

func renderConstructor(output *strings.Builder, operation model.LogicalOperation) {
	required := make([]model.Parameter, 0, len(operation.Parameters))
	for _, parameter := range operation.Parameters {
		if parameter.Required {
			required = append(required, parameter)
		}
	}
	if len(operation.Parameters) == 0 {
		output.WriteString("    /// Creates the parameter-free operation input.\n    #[must_use]\n    pub const fn new() -> Self { Self }\n\n")
		return
	}
	output.WriteString("    /// Creates an operation input. Explicit contract validation occurs during preparation.\n")
	output.WriteString("    #[must_use]\n")
	if len(required) == 0 {
		output.WriteString("    pub fn new() -> Self {\n")
	} else {
		output.WriteString("    pub fn new(")
		for index, parameter := range required {
			if index > 0 {
				output.WriteString(", ")
			}
			fmt.Fprintf(output, "%s: %s", parameter.RustName, constructorType(parameter))
		}
		output.WriteString(") -> Self {\n")
	}
	output.WriteString("        Self {\n")
	for _, parameter := range operation.Parameters {
		if !parameter.Required {
			fmt.Fprintf(output, "            %s: None,\n", parameter.RustName)
		} else if parameter.Shape == model.StringArray {
			fmt.Fprintf(output, "            %s: %s.into_iter().map(Into::into).collect(),\n", parameter.RustName, parameter.RustName)
		} else {
			fmt.Fprintf(output, "            %s: %s.into(),\n", parameter.RustName, parameter.RustName)
		}
	}
	output.WriteString("        }\n    }\n\n")
}

func renderParameterMethods(output *strings.Builder, parameter model.Parameter) {
	if parameter.Required {
		fmt.Fprintf(output, "    /// Returns the `%s` input.\n    #[must_use]\n    pub fn %s(&self) -> %s { %s }\n\n",
			parameter.WireName, parameter.RustName, getterType(parameter), getterExpression(parameter))
		return
	}
	fmt.Fprintf(output, "    /// Sets the optional `%s` input.\n    #[must_use]\n    pub fn with_%s(mut self, value: %s) -> Self { self.%s = Some(%s); self }\n\n",
		parameter.WireName, parameter.RustName, constructorType(parameter), parameter.RustName, ownedConversion(parameter, "value"))
	fmt.Fprintf(output, "    /// Returns the optional `%s` input when supplied.\n    #[must_use]\n    pub fn %s(&self) -> %s { %s }\n\n",
		parameter.WireName, parameter.RustName, getterType(parameter), getterExpression(parameter))
}

func renderCardinalityCheck(output *strings.Builder, parameter model.Parameter) {
	minimum, maximum := *parameter.MinItems, *parameter.MaxItems
	if parameter.Required {
		fmt.Fprintf(output, "        if !(%d..=%d).contains(&self.%s.len()) { return Err(PrepareError::InvalidCardinality { operation: identity, parameter: %s, minimum: %d, maximum: %d }); }\n",
			minimum, maximum, parameter.RustName, quote(parameter.WireName), minimum, maximum)
		return
	}
	fmt.Fprintf(output, "        if let Some(value) = &self.%s { if !(%d..=%d).contains(&value.len()) { return Err(PrepareError::InvalidCardinality { operation: identity, parameter: %s, minimum: %d, maximum: %d }); } }\n",
		parameter.RustName, minimum, maximum, quote(parameter.WireName), minimum, maximum)
}

func renderArrayElementCheck(output *strings.Builder, parameter model.Parameter) {
	if parameter.Required {
		fmt.Fprintf(output, "        for value in &self.%s {\n            require_nonempty(identity, %s, value)?;\n", parameter.RustName, quote(parameter.WireName))
		renderStringConstraintChecks(output, parameter, "value", "            ")
		output.WriteString("        }\n")
		return
	}
	fmt.Fprintf(output, "        if let Some(values) = &self.%s {\n            for value in values {\n                require_nonempty(identity, %s, value)?;\n", parameter.RustName, quote(parameter.WireName))
	renderStringConstraintChecks(output, parameter, "value", "                ")
	output.WriteString("            }\n        }\n")
}

func renderStringConstraintChecks(output *strings.Builder, parameter model.Parameter, value, indent string) {
	constraints := parameter.Constraints
	if constraints.MinLength != nil || constraints.MaxLength != nil {
		minimum, maximum := int64(0), "usize::MAX"
		if constraints.MinLength != nil {
			minimum = *constraints.MinLength
		}
		if constraints.MaxLength != nil {
			maximum = fmt.Sprint(*constraints.MaxLength)
		}
		fmt.Fprintf(output, "%srequire_length(identity, %s, %s, %d, %s)?;\n", indent, quote(parameter.WireName), value, minimum, maximum)
	}
	if constraints.Format != "" {
		fmt.Fprintf(output, "%srequire_format(identity, %s, %s, %s)?;\n", indent, quote(parameter.WireName), value, quote(constraints.Format))
	}
	if len(constraints.AllowedValues) > 0 {
		allowed := make([]string, 0, len(constraints.AllowedValues))
		for _, item := range constraints.AllowedValues {
			allowed = append(allowed, quote(item))
		}
		fmt.Fprintf(output, "%srequire_allowed(identity, %s, %s, &[%s])?;\n", indent, quote(parameter.WireName), value, strings.Join(allowed, ", "))
	}
	if constraints.DecimalMinimum != nil {
		maximum := "None"
		if constraints.DecimalMaximum != nil {
			maximum = fmt.Sprintf("Some(%d)", *constraints.DecimalMaximum)
		}
		fmt.Fprintf(output, "%srequire_decimal_range(identity, %s, %s, %d, %s)?;\n", indent, quote(parameter.WireName), value, *constraints.DecimalMinimum, maximum)
	}
}

func operationValidationImports(operations []model.LogicalOperation) []string {
	needed := map[string]bool{}
	for _, operation := range operations {
		for _, parameter := range operation.Parameters {
			constraints := parameter.Constraints
			needed["require_length"] = needed["require_length"] || constraints.MinLength != nil || constraints.MaxLength != nil
			needed["require_format"] = needed["require_format"] || constraints.Format != ""
			needed["require_allowed"] = needed["require_allowed"] || len(constraints.AllowedValues) > 0
			needed["require_decimal_range"] = needed["require_decimal_range"] || constraints.DecimalMinimum != nil
		}
	}
	var imports []string
	for _, name := range []string{"require_allowed", "require_decimal_range", "require_format", "require_length"} {
		if needed[name] {
			imports = append(imports, name)
		}
	}
	return imports
}

func renderQueryParameter(output *strings.Builder, parameter model.Parameter) {
	if parameter.Required {
		fmt.Fprintf(output, "        parameters.push(QueryParameter { name: %s, value: %s });\n", quote(parameter.WireName), queryValue(parameter, requiredParameterReference(parameter)))
		return
	}
	fmt.Fprintf(output, "        if let Some(value) = &self.%s { parameters.push(QueryParameter { name: %s, value: %s }); }\n",
		parameter.RustName, quote(parameter.WireName), queryValue(parameter, "value"))
}

func renderResponseGroup(source model.Model, operations []model.LogicalOperation, physical map[string]model.PhysicalOperation) (string, error) {
	dependencies := responseGroupDependencies(operations, physical)
	decodeImports := []string{"ObjectDecoder"}
	if dependencies.jsonArray {
		decodeImports = append(decodeImports, "decode_array")
	}
	if dependencies.xmlArray {
		decodeImports = append(decodeImports, "decode_xml_array")
	}
	if dependencies.status {
		decodeImports = append(decodeImports, "decode_source_status")
	}
	if dependencies.opaque {
		decodeImports = append(decodeImports, "decode_source_value")
	}
	if dependencies.string {
		decodeImports = append(decodeImports, "decode_string")
	}
	runtimeImports := []string{"ResponseDecodeError"}
	if dependencies.status {
		runtimeImports = append(runtimeImports, "SourceStatus")
	}
	runtimeImports = append(runtimeImports, "SourceValue")

	var output strings.Builder
	output.WriteString(header(source))
	output.WriteString("use std::collections::BTreeMap;\n\n")
	fmt.Fprintf(&output, "use crate::wire::decode::{%s};\n", strings.Join(decodeImports, ", "))
	fmt.Fprintf(&output, "use crate::{%s};\n\n", strings.Join(runtimeImports, ", "))
	for _, operation := range operations {
		for _, variant := range operation.Variants {
			if variant.Representation == model.RepresentationZIP {
				continue
			}
			physicalOperation := physical[variant.OperationID]
			shape, err := primaryResponseShape(physicalOperation)
			if err != nil {
				return "", err
			}
			if shape.Kind != "object" {
				return "", fmt.Errorf("render Rust SDK: structured response %s root is %s, want object", physicalOperation.OperationID, shape.Kind)
			}
			rootName := responseRootName(operation.RustName, variant.Representation)
			rootDecoder := responseDecoderName(rootName)
			arrayDecoder := "decode_array"
			objectConstructor := "new"
			if variant.Representation == model.RepresentationXML {
				arrayDecoder = "decode_xml_array"
				objectConstructor = "new_xml"
			}
			renderResponseObject(&output, rootName, rootDecoder+"_at", shape, arrayDecoder, objectConstructor)
			fmt.Fprintf(&output, "pub(crate) fn %s(value: SourceValue) -> Result<%s, ResponseDecodeError> {\n", rootDecoder, rootName)
			fmt.Fprintf(&output, "    %s(value, \"$\".to_owned())\n", rootDecoder+"_at")
			output.WriteString("}\n\n")
		}
	}
	return output.String(), nil
}

func primaryResponseShape(operation model.PhysicalOperation) (model.ResponseShape, error) {
	wantedMedia := map[model.Representation]string{
		model.RepresentationJSON: "application/json",
		model.RepresentationXML:  "application/xml",
		model.RepresentationZIP:  "application/zip",
	}[operation.PrimaryRepresentation]
	var selected *model.ResponseShape
	for _, response := range operation.Responses {
		for _, media := range response.Media {
			if media.Name != wantedMedia || media.ContentTypeStatus != "inferred-from-documented-output-format" {
				continue
			}
			if selected != nil {
				return model.ResponseShape{}, fmt.Errorf("render Rust SDK: response %s has multiple primary shapes", operation.OperationID)
			}
			shape := media.Shape
			selected = &shape
		}
	}
	if selected == nil {
		return model.ResponseShape{}, fmt.Errorf("render Rust SDK: response %s has no primary shape", operation.OperationID)
	}
	return *selected, nil
}

func renderResponseObject(output *strings.Builder, name, decoder string, shape model.ResponseShape, arrayDecoder, objectConstructor string) {
	renderRustDoc(output, "", shape.Description, "Generated OpenDART response object.")
	fmt.Fprintf(output, "#[derive(Clone, Debug, PartialEq)]\n#[cfg_attr(feature = \"serde-json\", derive(serde::Serialize))]\n#[non_exhaustive]\npub struct %s {\n", name)
	for _, property := range shape.Properties {
		renderRustDoc(output, "    ", property.Shape.Description, "Documented source field `"+property.Name+"`.")
		fmt.Fprintf(output, "    #[cfg_attr(feature = \"serde-json\", serde(rename = %s))]\n", quote(property.Name))
		fieldType := responseFieldType(name, property.RustName, property.Shape)
		if !responsePropertyRequired(shape, property.Name) {
			output.WriteString("    #[cfg_attr(feature = \"serde-json\", serde(skip_serializing_if = \"Option::is_none\"))]\n")
			fieldType = "Option<" + fieldType + ">"
		}
		fmt.Fprintf(output, "    pub %s: %s,\n", property.RustName, fieldType)
	}
	output.WriteString("    #[cfg_attr(feature = \"serde-json\", serde(flatten))]\n")
	output.WriteString("    additional_fields: BTreeMap<String, SourceValue>,\n")
	output.WriteString("}\n\n")
	fmt.Fprintf(output, "impl %s {\n", name)
	output.WriteString("    /// Returns an additive field not documented by this SDK version.\n    #[must_use]\n    pub fn additional_field(&self, name: &str) -> Option<&SourceValue> { self.additional_fields.get(name) }\n\n")
	output.WriteString("    /// Iterates additive fields in deterministic name order.\n    pub fn additional_fields(&self) -> impl Iterator<Item = (&str, &SourceValue)> { self.additional_fields.iter().map(|(name, value)| (name.as_str(), value)) }\n")
	output.WriteString("}\n\n")

	for _, property := range shape.Properties {
		childName := responseChildTypeName(name, property.RustName)
		childDecoder := decoder + "_" + property.RustName
		renderResponseNode(output, childName, childDecoder, property.Shape, arrayDecoder, objectConstructor)
	}

	fmt.Fprintf(output, "fn %s(value: SourceValue, path: String) -> Result<%s, ResponseDecodeError> {\n", decoder, name)
	fmt.Fprintf(output, "    let mut object = ObjectDecoder::%s(value, path)?;\n", objectConstructor)
	for _, property := range shape.Properties {
		method := "optional"
		if responsePropertyRequired(shape, property.Name) {
			method = "required"
		}
		fmt.Fprintf(output, "    let %s = object.%s(%s, %s)?;\n", property.RustName, method, quote(property.Name), responseNodeDecoder(decoder+"_"+property.RustName, property.Shape))
	}
	output.WriteString("    let additional_fields = object.finish();\n")
	fmt.Fprintf(output, "    Ok(%s {\n", name)
	for _, property := range shape.Properties {
		fmt.Fprintf(output, "        %s,\n", property.RustName)
	}
	output.WriteString("        additional_fields,\n    })\n}\n\n")
}

func renderResponseNode(output *strings.Builder, name, decoder string, shape model.ResponseShape, arrayDecoder, objectConstructor string) {
	switch shape.Kind {
	case "object":
		renderResponseObject(output, name, decoder, shape, arrayDecoder, objectConstructor)
	case "array":
		itemName := name + "Item"
		itemDecoder := decoder + "_item"
		renderResponseNode(output, itemName, itemDecoder, *shape.Items, arrayDecoder, objectConstructor)
		fmt.Fprintf(output, "fn %s(value: SourceValue, path: String) -> Result<Vec<%s>, ResponseDecodeError> {\n", decoder, responseShapeType(itemName, *shape.Items))
		fmt.Fprintf(output, "    %s(value, path, %s)\n", arrayDecoder, responseNodeDecoder(itemDecoder, *shape.Items))
		output.WriteString("}\n\n")
	}
}

func responseFieldType(parent, field string, shape model.ResponseShape) string {
	return responseShapeType(responseChildTypeName(parent, field), shape)
}

func responseShapeType(name string, shape model.ResponseShape) string {
	switch shape.Kind {
	case "object":
		return name
	case "array":
		itemName := name + "Item"
		return "Vec<" + responseShapeType(itemName, *shape.Items) + ">"
	case "string":
		if shape.OpenStatus {
			return "SourceStatus"
		}
		return "String"
	case "opaque":
		return "SourceValue"
	default:
		panic(fmt.Sprintf("unsupported generated response shape %q", shape.Kind))
	}
}

func responseNodeDecoder(generated string, shape model.ResponseShape) string {
	switch shape.Kind {
	case "object", "array":
		return generated
	case "string":
		if shape.OpenStatus {
			return "decode_source_status"
		}
		return "decode_string"
	case "opaque":
		return "decode_source_value"
	default:
		panic("unsupported generated response decoder")
	}
}

func responsePropertyRequired(shape model.ResponseShape, name string) bool {
	for _, required := range shape.Required {
		if required == name {
			return true
		}
	}
	return false
}

func responseChildTypeName(parent, field string) string {
	return parent + upperCamelIdentifier(field)
}

func renderRustDoc(output *strings.Builder, indent, description, fallback string) {
	description = strings.ReplaceAll(description, "\r", "")
	if strings.TrimSpace(description) == "" {
		description = fallback
	}
	for _, line := range strings.Split(description, "\n") {
		fmt.Fprintf(output, "%s/// %s\n", indent, safeRustDocText(line))
	}
}

func hasBinaryVariant(operations []model.LogicalOperation) bool {
	for _, operation := range operations {
		for _, variant := range operation.Variants {
			if variant.Representation == model.RepresentationZIP {
				return true
			}
		}
	}
	return false
}

func hasStructuredVariant(operations []model.LogicalOperation) bool {
	for _, operation := range operations {
		for _, variant := range operation.Variants {
			if variant.Representation != model.RepresentationZIP {
				return true
			}
		}
	}
	return false
}

func validateXMLRoots(source model.Model) error {
	for _, operation := range source.Physical {
		root := ""
		for _, response := range operation.Responses {
			for _, media := range response.Media {
				if media.Name != "application/xml" {
					continue
				}
				if media.Shape.XMLName == "" || media.Shape.XMLNodeType != "element" {
					return fmt.Errorf("render Rust SDK: response %s has invalid XML root metadata", operation.OperationID)
				}
				if root != "" && root != media.Shape.XMLName {
					return fmt.Errorf("render Rust SDK: response %s has inconsistent XML roots", operation.OperationID)
				}
				root = media.Shape.XMLName
			}
		}
	}
	return nil
}

func expectedXMLRoot(operation model.PhysicalOperation) string {
	root := ""
	for _, response := range operation.Responses {
		for _, media := range response.Media {
			if media.Name != "application/xml" {
				continue
			}
			root = media.Shape.XMLName
		}
	}
	return root
}

func rustOption(value string) string {
	if value == "" {
		return "None"
	}
	return "Some(" + quote(value) + ")"
}

type responseDependencies struct {
	jsonArray bool
	xmlArray  bool
	opaque    bool
	status    bool
	string    bool
}

func responseGroupDependencies(operations []model.LogicalOperation, physical map[string]model.PhysicalOperation) responseDependencies {
	var dependencies responseDependencies
	for _, operation := range operations {
		for _, variant := range operation.Variants {
			if variant.Representation == model.RepresentationZIP {
				continue
			}
			shape, err := primaryResponseShape(physical[variant.OperationID])
			if err != nil {
				continue
			}
			if responseShapeHasArray(shape) {
				switch variant.Representation {
				case model.RepresentationJSON:
					dependencies.jsonArray = true
				case model.RepresentationXML:
					dependencies.xmlArray = true
				}
			}
			collectResponseDependencies(shape, &dependencies)
		}
	}
	return dependencies
}

func collectResponseDependencies(shape model.ResponseShape, dependencies *responseDependencies) {
	switch shape.Kind {
	case "array":
		collectResponseDependencies(*shape.Items, dependencies)
	case "object":
		for _, property := range shape.Properties {
			collectResponseDependencies(property.Shape, dependencies)
		}
	case "opaque":
		dependencies.opaque = true
	case "string":
		if shape.OpenStatus {
			dependencies.status = true
		} else {
			dependencies.string = true
		}
	}
}

func responseShapeHasArray(shape model.ResponseShape) bool {
	switch shape.Kind {
	case "array":
		return true
	case "object":
		for _, property := range shape.Properties {
			if responseShapeHasArray(property.Shape) {
				return true
			}
		}
	}
	return false
}

func safeRustDocText(value string) string {
	var output strings.Builder
	for _, character := range value {
		if unicode.IsControl(character) || unicode.Is(unicode.Zl, character) || unicode.Is(unicode.Zp, character) {
			fmt.Fprintf(&output, `\u{%x}`, character)
		} else {
			output.WriteRune(character)
		}
	}
	safe := output.String()
	safe = strings.ReplaceAll(safe, "[", `\[`)
	safe = strings.ReplaceAll(safe, "]", `\]`)
	safe = strings.ReplaceAll(safe, "<", "&lt;")
	safe = strings.ReplaceAll(safe, ">", "&gt;")
	return bareRustDocURL.ReplaceAllStringFunc(safe, func(value string) string {
		return "`" + strings.ReplaceAll(value, "`", "\\`") + "`"
	})
}

var bareRustDocURL = regexp.MustCompile(`https?://[^\s]+`)

func hasRequiredParameter(parameters []model.Parameter) bool {
	for _, parameter := range parameters {
		if parameter.Required {
			return true
		}
	}
	return false
}

func hasOptionalParameter(parameters []model.Parameter) bool {
	for _, parameter := range parameters {
		if !parameter.Required {
			return true
		}
	}
	return false
}

func requiredParameterReference(parameter model.Parameter) string {
	if parameter.Shape == model.ScalarString {
		return "self." + parameter.RustName + ".as_str()"
	}
	return "&self." + parameter.RustName
}

func queryValue(parameter model.Parameter, reference string) string {
	if parameter.Shape == model.StringArray {
		return "QueryValue::CommaSeparated(" + reference + ")"
	}
	return "QueryValue::Scalar(" + reference + ")"
}

func rustParameterType(parameter model.Parameter) string {
	base := "String"
	if parameter.Shape == model.StringArray {
		base = "Vec<String>"
	}
	if !parameter.Required {
		return "Option<" + base + ">"
	}
	return base
}

func constructorType(parameter model.Parameter) string {
	if parameter.Shape == model.StringArray {
		return "impl IntoIterator<Item = impl Into<String>>"
	}
	return "impl Into<String>"
}

func getterType(parameter model.Parameter) string {
	if parameter.Required {
		if parameter.Shape == model.StringArray {
			return "&[String]"
		}
		return "&str"
	}
	if parameter.Shape == model.StringArray {
		return "Option<&[String]>"
	}
	return "Option<&str>"
}

func getterExpression(parameter model.Parameter) string {
	if parameter.Required {
		if parameter.Shape == model.StringArray {
			return "&self." + parameter.RustName
		}
		return "&self." + parameter.RustName
	}
	if parameter.Shape == model.StringArray {
		return "self." + parameter.RustName + ".as_deref()"
	}
	return "self." + parameter.RustName + ".as_deref()"
}

func ownedConversion(parameter model.Parameter, value string) string {
	if parameter.Shape == model.StringArray {
		return value + ".into_iter().map(Into::into).collect()"
	}
	return value + ".into()"
}

func expectedConstant(representations []model.Representation) string {
	if len(representations) == 1 && representations[0] == model.RepresentationJSON {
		return "JSON_ONLY"
	}
	if len(representations) == 1 && representations[0] == model.RepresentationXML {
		return "XML_ONLY"
	}
	if len(representations) == 2 && representations[0] == model.RepresentationZIP && representations[1] == model.RepresentationXML {
		return "ZIP_OR_XML"
	}
	panic(fmt.Sprintf("unsupported normalized representation set: %#v", representations))
}

func rustRepresentation(value model.Representation) string {
	switch value {
	case model.RepresentationJSON:
		return "Json"
	case model.RepresentationXML:
		return "Xml"
	case model.RepresentationZIP:
		return "Zip"
	default:
		panic("unsupported normalized representation")
	}
}

func preparationMethod(value model.Representation) string {
	switch value {
	case model.RepresentationJSON:
		return "prepare_json"
	case model.RepresentationXML:
		return "prepare_xml"
	case model.RepresentationZIP:
		return "prepare_zip"
	default:
		panic("unsupported normalized representation")
	}
}

func responseRootName(operation string, representation model.Representation) string {
	return operation + rustRepresentation(representation) + "Response"
}

func responseDecoderName(response string) string {
	return "decode_" + lowerSnake(response)
}

func upperCamelIdentifier(value string) string {
	var output strings.Builder
	upper := true
	for _, character := range value {
		if character == '_' {
			upper = true
			continue
		}
		if upper {
			output.WriteRune(unicode.ToUpper(character))
			upper = false
		} else {
			output.WriteRune(character)
		}
	}
	return output.String()
}

func lowerSnake(value string) string {
	var output strings.Builder
	for index, character := range value {
		if unicode.IsUpper(character) {
			if index > 0 {
				output.WriteByte('_')
			}
			output.WriteRune(unicode.ToLower(character))
		} else {
			output.WriteRune(character)
		}
	}
	return output.String()
}

func validateRustSymbols(source model.Model) error {
	requestReserved := map[string]string{
		"OperationIdentity":     "runtime import",
		"PrepareError":          "runtime import",
		"PreparedBinaryRequest": "runtime import",
		"PreparedRequest":       "runtime import",
		"QueryParameter":        "runtime import",
		"QueryValue":            "runtime import",
		"Representation":        "runtime import",
		"RequestParts":          "runtime import",
	}
	publicRequests := make(map[string]string, len(source.Logical))
	publicResponses := make(map[string]string)
	physical := make(map[string]model.PhysicalOperation, len(source.Physical))
	for _, operation := range source.Physical {
		physical[operation.OperationID] = operation
	}
	for _, operation := range source.Logical {
		if previous := requestReserved[operation.RustName]; previous != "" {
			return fmt.Errorf("render Rust SDK: request type %s collides with %s", operation.RustName, previous)
		}
		if previous := publicRequests[operation.RustName]; previous != "" {
			return fmt.Errorf("render Rust SDK: request type %s is shared by %s and %s", operation.RustName, previous, operation.ID)
		}
		publicRequests[operation.RustName] = operation.ID
		for _, variant := range operation.Variants {
			if variant.Representation == model.RepresentationZIP {
				continue
			}
			shape, err := primaryResponseShape(physical[variant.OperationID])
			if err != nil {
				return err
			}
			root := responseRootName(operation.RustName, variant.Representation)
			if err := collectResponseSymbols(publicResponses, root, variant.OperationID, shape); err != nil {
				return err
			}
		}
	}
	return nil
}

func collectResponseSymbols(symbols map[string]string, name, operation string, shape model.ResponseShape) error {
	switch shape.Kind {
	case "object":
		if previous := symbols[name]; previous != "" {
			return fmt.Errorf("render Rust SDK: response type %s is shared by %s and %s", name, previous, operation)
		}
		symbols[name] = operation
		for _, property := range shape.Properties {
			if property.RustName == "additional_field" || property.RustName == "additional_fields" {
				return fmt.Errorf("render Rust SDK: response field %s collides with generated evidence accessors for %s", property.Name, operation)
			}
			if err := collectResponseSymbols(symbols, responseChildTypeName(name, property.RustName), operation, property.Shape); err != nil {
				return err
			}
		}
	case "array":
		return collectResponseSymbols(symbols, name+"Item", operation, *shape.Items)
	}
	return nil
}

func quote(value string) string {
	var output strings.Builder
	output.WriteByte('"')
	for _, character := range value {
		switch character {
		case '"':
			output.WriteString(`\"`)
		case '\\':
			output.WriteString(`\\`)
		case '\n':
			output.WriteString(`\n`)
		case '\r':
			output.WriteString(`\r`)
		case '\t':
			output.WriteString(`\t`)
		default:
			if character >= 0x20 && character <= 0x7e {
				output.WriteRune(character)
			} else {
				fmt.Fprintf(&output, `\u{%x}`, character)
			}
		}
	}
	output.WriteByte('"')
	return output.String()
}
